<?php

/**
 * BaseCourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $teacher_id
 * @property integer $semester
 * @property Teacher $Teacher
 * 
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method integer getTeacherId()   Returns the current record's "teacher_id" value
 * @method integer getSemester()    Returns the current record's "semester" value
 * @method Teacher getTeacher()     Returns the current record's "Teacher" value
 * @method Course  setName()        Sets the current record's "name" value
 * @method Course  setDescription() Sets the current record's "description" value
 * @method Course  setTeacherId()   Sets the current record's "teacher_id" value
 * @method Course  setSemester()    Sets the current record's "semester" value
 * @method Course  setTeacher()     Sets the current record's "Teacher" value
 * 
 * @package    symfony-university
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('teacher_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Teacher', array(
             'local' => 'teacher_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}