<?php

/**
 * BaseTeacherPublication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $authors
 * @property integer $publicationYear
 * @property integer $teacher_id
 * @property Teacher $Teacher
 * 
 * @method string             getName()            Returns the current record's "name" value
 * @method string             getAuthors()         Returns the current record's "authors" value
 * @method integer            getPublicationYear() Returns the current record's "publicationYear" value
 * @method integer            getTeacherId()       Returns the current record's "teacher_id" value
 * @method Teacher            getTeacher()         Returns the current record's "Teacher" value
 * @method TeacherPublication setName()            Sets the current record's "name" value
 * @method TeacherPublication setAuthors()         Sets the current record's "authors" value
 * @method TeacherPublication setPublicationYear() Sets the current record's "publicationYear" value
 * @method TeacherPublication setTeacherId()       Sets the current record's "teacher_id" value
 * @method TeacherPublication setTeacher()         Sets the current record's "Teacher" value
 * 
 * @package    symfony-university
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeacherPublication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teacher_publication');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('authors', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('publicationYear', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('teacher_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Teacher', array(
             'local' => 'teacher_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}