<?php

/**
 * BaseTeacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $degree
 * @property string $interests
 * @property Doctrine_Collection $TeacherPublication
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getDegree()             Returns the current record's "degree" value
 * @method string              getInterests()          Returns the current record's "interests" value
 * @method Doctrine_Collection getTeacherPublication() Returns the current record's "TeacherPublication" collection
 * @method Teacher             setName()               Sets the current record's "name" value
 * @method Teacher             setDegree()             Sets the current record's "degree" value
 * @method Teacher             setInterests()          Sets the current record's "interests" value
 * @method Teacher             setTeacherPublication() Sets the current record's "TeacherPublication" collection
 * 
 * @package    symfony-university
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeacher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teacher');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('degree', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('interests', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TeacherPublication', array(
             'local' => 'id',
             'foreign' => 'teacher_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}