<?php

/**
 * CourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Course');
    }
}