<?php

/**
 * TeacherPublicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeacherPublicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeacherPublicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeacherPublication');
    }
}