<?php

/**
 * TeacherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeacherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeacherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Teacher');
    }

    public function getTeachersOrderedByPriority()
    {
      $query = $this->createQuery('t')
        ->orderBy('t.priority ASC');
      return $query->execute();
    }
}