News:
        actAs : {Timestampable : ~}
        columns :
                title: {type: string(255), notnull: true}
                body: {type: string(10000), notnull: true}

Teacher:
        actAs : {Timestampable : ~}
        columns :
                name: {type: string(255), notnull: true}
                degree: {type: string(50), notnull: true}
                interests: {type: string(255), notnull: false}

TeacherPublication:
        actAs: {Timestampable: ~}
        columns:
                name: {type: string(255), notnull: true}
                authors: {type: string(255), notnull: false}
                publicationYear: {type: integer, notnull: true}
                teacher_id: {type: integer, notnull: true}
        relations:
                Teacher: {onDelete: CASCADE, local: teacher_id, foreign: id}
